version: '3.9'

services:
  roadmap:
    build: .
    environment:
      - APP_PORT=$APP_PORT
      - SQLConnectionString=$SQL_CONNECTION_STRING
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - db
  db:
    image: 'mcr.microsoft.com/azure-sql-edge'
    environment:
      SA_PASSWORD: "ProductApi(!)"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"