version: '3.9'

services:
  user-service:
    build: .
    environment:
      - APP_PORT=$APP_PORT
      - SQLConnectionString=$SQL_CONNECTION_STRING
      - ASPNETCORE_URLS=http://0.0.0.0:${APP_PORT}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - msserver
  msserver:
    image: 'mcr.microsoft.com/azure-sql-edge'
    environment:
      SA_PASSWORD: "ProductApi(!)"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"